### ISSUE TITLE
Does not work on namespaced classes

### ISSUE THREAD

**Issue by MBraedley** [SeifSarsar/GS-Assist#1]
I tried using this for a class declaration contained in a nested namespace (C++17 style, i.e. `namespace a::b::c`) and received the error "Can not find a class in the header file."  Commenting out the namespace temporarily allowed me to create the getters and setters, but this shouldn't be necessary.

**Comment by SeifSarsar** [comment]
Thank you very much for your feedback. I will fix this problem as soon as possible!

**Comment by SeifSarsar** [comment]
The error has been fixed by changing the way this tool works. All you have to do is to click inside the brackets of a class in order to add the functions.
